[package]
name = "juke_allocator"
version = "0.1.0"
edition = "2021"
#build = "build_"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.8"
libc = "0.2.0"

[build-dependencies]
cmake = "0.1"


